# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on: [push, pull_request]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #这里就是一个复用的 action，它会把仓库代码检出到 runner 中。
      - uses: actions/setup-node@v3 #这里也是一个复用的 action，它的作用是安装一个指定版本的 node。
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Install Dependencies
        run: pnpm install  --no-frozen-lockfile

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBCITOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
