# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on: [push, pull_request]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #这里就是一个复用的 action，它会把仓库代码检出到 runner 中。
      - uses: actions/setup-node@v3 #这里也是一个复用的 action，它的作用是安装一个指定版本的 node。
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm install -g pnpm
      - run: pnpm install

      - uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm run release
        env:
          NPM_TOKEN: ${{ secrets.NPMPUBLISHTOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
